# Generated by Django 5.2.17 on 2026-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('rack_id', models.CharField(blank=True, max_length=32)),
                ('price_per_gallon', models.DecimalField(decimal_places=5, max_digits=8)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_per_gallon'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='routing_fue_latitud_6dc999_idx'), models.Index(fields=['city', 'state'], name='routing_fue_city_c91742_idx')],
            },
        ),
    ]
